import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface HookInstallOptions {
  repoPath: string;
  bindingId: string;
  coreServiceUrl: string;
}

const HOOK_NAME = 'post-commit';

export function installLocalHook(options: HookInstallOptions): void {
  const hooksDir = join(options.repoPath, '.git', 'hooks');
  mkdirSync(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, HOOK_NAME);
  const script = `#!/bin/sh
# Generated by feishu-md-repo for binding ${options.bindingId}
curl -s -X POST "${options.coreServiceUrl}/api/hooks/local" \\
  -H "Content-Type: application/json" \\
  -d "{\\"bindingId\\":\\"${options.bindingId}\\",\\"trigger\\":\\"git\\"}" >/dev/null 2>&1 || true
`;

  writeFileSync(hookPath, script, 'utf8');
  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // Windows may not support chmod; hook can still run via sh
  }
}

export function removeLocalHook(repoPath: string): void {
  const hookPath = join(repoPath, '.git', 'hooks', HOOK_NAME);
  if (!existsSync(hookPath)) return;

  try {
    const content = readFileSync(hookPath, 'utf8');
    if (!content.includes('Generated by feishu-md-repo')) return;
    unlinkSync(hookPath);
  } catch {
    // ignore
  }
}
